### ISSUE TITLE
Shift away from transforms.ToTensor()

### ISSUE THREAD

**Issue by im-a-jin** [MTNeuro/MTNeuro#14]
Currently, users are directed to use `transforms.ToTensor()` if they do not want to do any data augmentations/transforms. They are also told to apply this transform to both the image and mask arrays which may prove confusing for task 1.

`transforms.ToTensor()` by default transforms H x W x C to C x H x W and scales the image to the range [0.0, 1.0] _if_ the input numpy array has dtype = np.uint8.

The BossDB data is stored in Z x Y x X format which the `BossDBDataset` takes into account and re-transposes the axes after passing the image through `transforms.ToTensor()`. The transform is also applied if the data is 3D which doesn't seem correct since torchvision only supports 2D augmentations.

I currently have a [pull request](https://github.com/MTNeuro/MTNeuro/pull/10) addressing this problem for task 2. However, the problem still exists for task 1 due to `torch.mode` being used to extract macroscopic region labels from the pixel-level roi labeling.

A quick fix to make this more readable at the user-level would be to check if the provided transforms are `None`, and if they are, to apply `torch.ToTensor()` internally.

**Comment by mazabou** [comment]
Resolved with PR #27
